"""tools.video 双语投影与一致性单元测试（FR-005 / FR-012 / FR-021、SC-003、V9）。

覆盖 tasks.md T034 的三条断言：
  ① 按 zh / en 投影后分镜数量与 order 序列逐一对应（SC-003）；
  ② 语言纯净性 —— zh 文案不含白名单外的 ASCII 单词、en 文案不含 CJK（FR-021）；
  ③ 缺任一语言时 content.py 报错并指明「文件 + 分镜/候选 id + 语言」；
另覆盖 T037/T050 的校验内核 V9（两版分镜数/顺序一致）与 V12（历史 sha256 未变）的判定分支。

无 pytest 依赖，可直接运行：
    venv\\Scripts\\python.exe tests\\test_video_bilingual.py
"""
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tools.video import cli  # noqa: E402
from tools.video import content as content_mod  # noqa: E402
from tools.video import manifest  # noqa: E402

CANDIDATES_ONE = """
[[candidate]]
id = "cand_a"
expect_chart = true
  [candidate.prompt]
  zh = "绘制分组数据的分布图"
  en = "Plot the distribution of grouped data"
"""

MANUAL_ONE = """
[[manual]]
id = "manual_demo"
chart_type = "bar"
x_field = "year"
y_fields = ["count"]
  [manual.title]
  zh = "年度分布"
  en = "Yearly distribution"
"""

NARRATION_ZH = "这一段旁白用来说明平台如何把一句提问变成一张图表，用于双语一致性校验。"
NARRATION_EN = "This narration explains how the platform turns a question into a chart for the bilingual check."


def _scenes() -> str:
    return f"""
[meta]
version = "1.0.0"
target_duration_sec = [100, 200]
languages = ["zh", "en"]

  [meta.title]
  zh = "示例标题"
  en = "Sample title"

[[shot]]
id = "show_a"
order = 1
kind = "chart_showcase"
source = "cand_a"
zoom = "in"
  [shot.title]
  zh = "图表甲"
  en = "Chart A"
  [shot.narration]
  zh = "{NARRATION_ZH}"
  en = "{NARRATION_EN}"
"""


def _write(tmp: str, scenes: str, candidates: str) -> Path:
    root = Path(tmp)
    (root / "scenes.toml").write_text(scenes, encoding="utf-8")
    (root / "candidates.toml").write_text(candidates, encoding="utf-8")
    return root


# ── ① SC-003：投影不改变结构 ────────────────────────────────────────────────
def test_projection_keeps_shot_count_and_order():
    content = content_mod.load_content()  # 仓库内真实内容定义
    zh = [(s.id, s.order, content_mod.localize(s.title, "zh"),
           content_mod.localize(s.narration, "zh")) for s in content.shots]
    en = [(s.id, s.order, content_mod.localize(s.title, "en"),
           content_mod.localize(s.narration, "en")) for s in content.shots]
    assert [x[:2] for x in zh] == [x[:2] for x in en], "中英投影的 id/order 序列必须逐一对应"
    assert [s.order for s in content.shots] == list(range(1, len(content.shots) + 1)), "order 必须是 1..N 连续"
    assert all(a[2] != b[2] and a[3] != b[3] for a, b in zip(zh, en)), "中英文案必须各自独立、不得复用"


def test_projection_keeps_bilingual_demo_and_purity():
    content = content_mod.load_content()
    kinds = [s.kind for s in content.shots]
    assert kinds.count("bilingual_demo") == 1, "必须恰好一个 bilingual_demo 分镜（FR-012）"
    for shot in content.shots:
        for text in (shot.title, shot.narration, shot.subtitle):
            if text is not None:
                content_mod.validate_localized_text(text, f"分镜 {shot.id}")


def test_projection_rejects_unknown_language():
    content = content_mod.load_content()
    try:
        content_mod.localize(content.shots[0].title, "fr")
    except content_mod.ContentError as exc:
        assert exc.code == "content_invalid", exc.code
        assert "fr" in exc.message, exc.message
    else:
        raise AssertionError("不支持的语言必须报错")


# ── ② 语言纯净性 ────────────────────────────────────────────────────────────
def test_language_purity_rejects_english_in_chinese():
    bad = content_mod.LocalizedText(zh="这段旁白出现了 Plot the chart 这样的英文句子，属于语言混用。",
                                    en="Clean English.")
    try:
        content_mod.validate_localized_text(bad, "分镜 show_a.narration")
    except content_mod.ContentError as exc:
        assert exc.code == "content_invalid", exc.code
        assert "英文单词" in exc.message and "show_a" in exc.message, exc.message
    else:
        raise AssertionError("zh 出现英文单词必须报错（FR-021）")


def test_language_purity_rejects_cjk_in_english():
    bad = content_mod.LocalizedText(zh="纯中文旁白。", en="This narration 混入了中文字符 and should fail.")
    try:
        content_mod.validate_localized_text(bad, "分镜 show_a.narration")
    except content_mod.ContentError as exc:
        assert exc.code == "content_invalid", exc.code
        assert "中文字符" in exc.message and "show_a" in exc.message, exc.message
    else:
        raise AssertionError("en 出现 CJK 必须报错（FR-021）")


def test_language_purity_allows_whitelisted_terms():
    ok = content_mod.LocalizedText(zh="图表由 Plotly 渲染，SQL 由 AI 生成。",
                                   en="Rendered by Plotly; SQL is generated by AI.")
    content_mod.validate_localized_text(ok, "分镜 show_a.narration")



# ── ③ 缺语言时指名「文件 + id + 语言」 ──────────────────────────────────────
def test_missing_shot_language_names_file_id_and_language():
    scenes = _scenes().replace(f'  en = "{NARRATION_EN}"\n', "")
    with tempfile.TemporaryDirectory() as tmp:
        root = _write(tmp, scenes, CANDIDATES_ONE + MANUAL_ONE)
        try:
            content_mod.load_content(root)
        except content_mod.ContentError as exc:
            assert exc.code == "content_invalid", exc.code
            assert "scenes.toml" in exc.message, f"应指明文件：{exc.message}"
            assert "show_a" in exc.message, f"应指明分镜 id：{exc.message}"
            assert "en" in exc.message, f"应指明缺失语言：{exc.message}"
        else:
            raise AssertionError("缺 en 旁白必须报错")


def test_missing_candidate_language_names_file_id_and_language():
    candidates = CANDIDATES_ONE.replace('  en = "Plot the distribution of grouped data"\n', "") + MANUAL_ONE
    with tempfile.TemporaryDirectory() as tmp:
        root = _write(tmp, _scenes(), candidates)
        try:
            content_mod.load_content(root)
        except content_mod.ContentError as exc:
            assert exc.code == "content_invalid", exc.code
            assert "candidates.toml" in exc.message, f"应指明文件：{exc.message}"
            assert "cand_a" in exc.message, f"应指明候选 id：{exc.message}"
            assert "en" in exc.message, f"应指明缺失语言：{exc.message}"
        else:
            raise AssertionError("候选缺 en 必须报错")


# ── V9 / V12：校验内核的判定分支 ────────────────────────────────────────────
def _stub_hashes(baseline: dict, current: dict):
    """替换 V12 的外部数据源（历史 sha256 基线），返回还原函数。"""
    orig_baseline = cli._load_hash_baseline
    orig_current = manifest.existing_video_hashes
    cli._load_hash_baseline = lambda: (Path("baseline.json"), dict(baseline))
    manifest.existing_video_hashes = lambda exclude_run=None: dict(current)
    return lambda: (setattr(cli, "_load_hash_baseline", orig_baseline),
                    setattr(manifest, "existing_video_hashes", orig_current))


def _video(lang: str, order_seq: list, duration: float) -> dict:
    return {"path": f"demo-{lang}.mp4", "language": lang, "duration_sec": duration,
            "scene_count": len(order_seq),
            "source_shots": [{"order": o} for o in order_seq]}


def _core_checks(videos: list, *, baseline: dict | None = None, current: dict | None = None) -> list:
    content = content_mod.load_content()
    baseline = {"run_old/demo-zh.mp4": "h1"} if baseline is None else baseline
    current = {"run_old/demo-zh.mp4": "h1"} if current is None else current
    restore = _stub_hashes(baseline, current)
    try:
        return cli._verify_core_checks(content, manifest.run_dir("20261005-000000-abc1234"),
                                       {"produced_videos": videos, "shots": []}, {"candidates": []})
    finally:
        restore()


def _by_id(checks: list, check_id: str) -> dict:
    for item in checks:
        if item["id"] == check_id:
            return item
    raise AssertionError(f"未产出校验项 {check_id}")


def _mid_duration() -> float:
    low, high = content_mod.load_content().target_duration
    return (low + high) / 2


def test_v9_accepts_matching_bilingual_pair():
    seq = list(range(1, 11))
    checks = _core_checks([_video("zh", seq, _mid_duration()), _video("en", seq, _mid_duration())])
    assert _by_id(checks, "V9")["ok"] is True, _by_id(checks, "V9")["detail"]
    assert _by_id(checks, "V8")["ok"] is True, _by_id(checks, "V8")["detail"]


def test_v9_accepts_single_language_build():
    checks = _core_checks([_video("zh", list(range(1, 11)), _mid_duration())])
    assert _by_id(checks, "V9")["ok"] is True, _by_id(checks, "V9")["detail"]


def test_v9_rejects_divergent_scene_count_or_order():
    seq = list(range(1, 11))
    checks = _core_checks([_video("zh", seq, _mid_duration()), _video("en", list(range(2, 12)), _mid_duration())])
    assert _by_id(checks, "V9")["ok"] is False, "顺序不一致必须判失败"
    checks = _core_checks([_video("zh", seq, _mid_duration()), _video("en", seq[:9], _mid_duration())])
    assert _by_id(checks, "V9")["ok"] is False, "分镜数不一致必须判失败"


def test_v8_rejects_out_of_range_duration():
    low, _high = content_mod.load_content().target_duration
    checks = _core_checks([_video("zh", list(range(1, 11)), low * 0.5)])
    assert _by_id(checks, "V8")["ok"] is False, "时长越界必须判失败"


def test_v12_accepts_unchanged_history():
    checks = _core_checks([_video("zh", [1], _mid_duration())])
    assert _by_id(checks, "V12")["ok"] is True, _by_id(checks, "V12")["detail"]


def test_v12_rejects_changed_or_missing_history():
    videos = [_video("zh", [1], _mid_duration())]
    changed = _core_checks(videos, current={"run_old/demo-zh.mp4": "h2"})
    assert _by_id(changed, "V12")["ok"] is False, "sha256 变化必须判失败"
    missing = _core_checks(videos, current={})
    assert _by_id(missing, "V12")["ok"] is False, "历史成片缺失必须判失败"


if __name__ == "__main__":
    fns = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    failed = 0
    for fn in fns:
        try:
            fn()
            print(f"PASS {fn.__name__}")
        except AssertionError as e:
            failed += 1
            print(f"FAIL {fn.__name__}: {e}")
        except Exception as e:  # noqa: BLE001
            failed += 1
            print(f"ERROR {fn.__name__}: {type(e).__name__}: {e}")
    print(f"\n{len(fns) - failed}/{len(fns)} passed")
    sys.exit(1 if failed else 0)
